source 'https://rubygems.org'

#Task automation
gem 'rake', '~> 11.2'

#Test
gem 'minitest', '~> 5.9'

#Background Process and Multiple Thread
gem 'sidekiq', '~> 4.1'

#Folder listener
gem 'listen', '~> 3.0'
